In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D

import pickle



In [2]:
pickle_in = open("X.pickle", "rb")
X = pickle.load(pickle_in)

pickle_in = open("Y.pickle", "rb")
Y = pickle.load(pickle_in)

X = X/255.0

print(X[0])
print(Y[0])
print(X.shape)
print(X.shape[1:])

[[[0.17647059]
  [0.18823529]
  [0.20784314]
  ...
  [0.57647059]
  [0.58431373]
  [0.6       ]]

 [[0.22352941]
  [0.23137255]
  [0.2745098 ]
  ...
  [0.59607843]
  [0.58823529]
  [0.61176471]]

 [[0.23137255]
  [0.25098039]
  [0.23137255]
  ...
  [0.60784314]
  [0.60392157]
  [0.61960784]]

 ...

 [[0.62352941]
  [0.60784314]
  [0.53333333]
  ...
  [0.58431373]
  [0.65490196]
  [0.65098039]]

 [[0.59215686]
  [0.56862745]
  [0.55294118]
  ...
  [0.57254902]
  [0.65098039]
  [0.6627451 ]]

 [[0.58431373]
  [0.5254902 ]
  [0.51764706]
  ...
  [0.56078431]
  [0.63921569]
  [0.64313725]]]
1
(102, 50, 50, 1)
(50, 50, 1)


In [3]:
model = Sequential()

model.add(Conv2D(256, (3,3), input_shape = X.shape[1:]))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size = (2,2)))

model.add(Conv2D(256, (3,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size = (2,2)))

model.add(Flatten())
model.add(Dense(64))
model.add(Dense(1))
model.add(Activation('sigmoid'))

model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
model.fit(X, Y, batch_size = 10, epochs = 10)
model.summary()


Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
Epoch 1/10
102/102 [==============================] - 4s 39ms/sample - loss: 0.8399 - acc: 0.5196
Epoch 2/10
102/102 [==============================] - 3s 33ms/sample - loss: 0.6960 - acc: 0.5098
Epoch 3/10
102/102 [==============================] - 3s 33ms/sample - loss: 0.6814 - acc: 0.5980
Epoch 4/10
102/102 [==============================] - 3s 33ms/sample - loss: 0.6509 - acc: 0.6569
Epoch 5/10
102/102 [==============================] - 3s 33ms/sample - loss: 0.5915 - acc: 0.6569
Epoch 6/10
102/102 [==============================] - 4s 34ms/sample - loss: 0.4842 - acc: 0.7647
Epoch 7/10
102/102 [==============================] - 3s 33ms/sample - loss: 0.3894 - acc: 0.8039
Epoch 8/10
102/102 [==============================] - 3s 33ms/sample - loss: 0.3567 - acc: 0.8824
Epoch 9/10
102/102 [==============================] - 3s 33ms/sample - loss: 0.2709 - acc: 0.882

In [14]:
import os
import cv2
import matplotlib.pyplot as plt
import numpy as np

IMG_SIZE = 50
TEST_IMAGES_DIR = "C:/Users/LattePanda/Documents/Test_images/"
CATEGORIES = ["Dog", "Cat"]
testImages =[]
for index in CATEGORIES:
    path = os.path.join(TEST_IMAGES_DIR, index)
    for imageFileName in os.listdir(path):
        imageArray = cv2.imread(os.path.join(path,imageFileName), cv2.IMREAD_GRAYSCALE) 
        #plt.imshow(imageArray, cmap = 'gray')
        #plt.show()
        imageArray = cv2.resize(imageArray, (IMG_SIZE, IMG_SIZE))
        testImages.append(imageArray)
        
testImages = np.array(testImages).reshape(-1, IMG_SIZE, IMG_SIZE, 1)
print(testImages.shape)
prediction = model.predict(testImages)
print(prediction)
whichOne = np.int8(prediction)
print(CATEGORIES[whichOne[0][0]])
print(CATEGORIES[whichOne[11][0]])

(20, 50, 50, 1)
[[0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
Dog
Cat
